# Generated by Django 4.2.27 on 2026-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0220_new_ioi_hidden_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('atcoder', 'AtCoder'), ('default', 'Default'), ('ecoo', 'ECOO'), ('icpc', 'ICPC'), ('ioi', 'IOI (pre-2016)'), ('ioi16', 'IOI'), ('new_ioi', 'New IOI'), ('vnoj', 'VNOJ')], default='default', help_text='The contest format module to use.', max_length=64, verbose_name='contest format'),
        ),
    ]
