# Generated by Django 4.2.27 on 2026-05-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0221_alter_contest_format_name'),
        ('judge', '0221_contest_category_path_slug'),
    ]

    operations = [
    ]
