# Generated by Django 4.2.27 on 2026-08-02

import django.core.validators
from django.db import migrations, models

import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0225_testcase_download_log_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(
                blank=True,
                help_text="Upload a PNG image to use as this organization's navbar logo.",
                upload_to=judge.models.profile.organization_logo_upload_path,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])],
                verbose_name='organization logo',
            ),
        ),
    ]
