# Generated by Django 4.2.30 on 2026-08-02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import judge.models.interface


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('judge', '0226_organization_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(
                    blank=True,
                    help_text='Upload a PNG image for the navbar. Clear it to restore the default site logo.',
                    upload_to=judge.models.interface.site_logo_upload_path,
                    validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])],
                    verbose_name='site logo',
                )),
                ('site', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='branding',
                    to='sites.site',
                    verbose_name='site',
                )),
            ],
            options={
                'verbose_name': 'site branding',
                'verbose_name_plural': 'site branding',
            },
        ),
    ]
