# Generated by Django 5.2.16 on 2026-09-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0229_contest_category_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestcategory',
            name='contests',
            field=models.ManyToManyField(blank=True, help_text='Users allowed by this category can view all assigned contests, including private or unpublished contests.', related_name='categories', to='judge.contest', verbose_name='contests'),
        ),
        migrations.AlterField(
            model_name='contestcategory',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Used only when no organizations or groups are selected. Private categories are visible to their creator.', verbose_name='publicly visible'),
        ),
        migrations.AlterField(
            model_name='contestcategory',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Members of any selected organization or group may view this category and its assigned contests.', to='judge.organization', verbose_name='organizations'),
        ),
        migrations.CreateModel(
            name='ContestCategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='group name')),
                ('users', models.ManyToManyField(blank=True, help_text='Manually selected users. Group names and membership are visible only in the admin.', related_name='+', to='judge.profile', verbose_name='users')),
            ],
            options={
                'verbose_name': 'category group',
                'verbose_name_plural': 'category groups',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='contestcategory',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Members of any selected group or organization may view this category and its assigned contests. Groups are not displayed to users.', related_name='categories', to='judge.contestcategorygroup', verbose_name='groups'),
        ),
    ]
