# Generated by Django 5.2.16 on 2026-09-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_contest_category_sharing_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestcategory',
            name='contests',
            field=models.ManyToManyField(blank=True, help_text='Organization and group members selected here or in an ancestor category can view assigned private or unpublished contests. Making the category public does not publish its contests.', related_name='categories', to='judge.contest', verbose_name='contests'),
        ),
        migrations.AlterField(
            model_name='contestcategory',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Members of any selected group or organization may view this category, its subcategories, and all contests assigned to them. Groups are not displayed to users.', related_name='categories', to='judge.contestcategorygroup', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='contestcategory',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Members of any selected organization or group may view this category, its subcategories, and all contests assigned to them.', to='judge.organization', verbose_name='organizations'),
        ),
    ]
